name: Node.js CI

on:
  pull_request:
    branches: [ "main" ]
  workflow_call:
    secrets:
      STRYKER_DASHBOARD_API_KEY:
        required: true

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x, 24.x, 26.x]

    steps:
    - uses: actions/checkout@v7
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v7
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build
    - run: npm run lint
    - if: ${{ matrix.node-version != '26.x' }}
      run: npm test
    - if: ${{ matrix.node-version == '26.x' }}
      run: npm test -- --coverage
    - if: ${{ matrix.node-version == '26.x' }}
      uses: coverallsapp/github-action@v2
    - if: ${{ matrix.node-version == '26.x' }}
      run: npm run test:mutation
      env:
        STRYKER_DASHBOARD_API_KEY: ${{ secrets.STRYKER_DASHBOARD_API_KEY }}
